
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asifc
 */
public class AppJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AppJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        encryptionTab = new javax.swing.JPanel();
        inputPlainText = new javax.swing.JTextArea();
        outputEncryptedText = new javax.swing.JTextArea();
        encryptionEnterStatementLabel = new javax.swing.JLabel();
        encryptionEncryptedTextLabel = new javax.swing.JLabel();
        encryptionCopyLabel = new javax.swing.JLabel();
        encryptButton = new javax.swing.JButton();
        decryptionTab = new javax.swing.JPanel();
        decryptionDecryptedText = new javax.swing.JTextArea();
        decryptionEnterDecryptedText = new javax.swing.JTextArea();
        decryptButton = new javax.swing.JButton();
        decryptionEnterDecryptedLabel = new javax.swing.JLabel();
        decryptionDecryptedTextLabel = new javax.swing.JLabel();
        decryptionPasteLabel = new javax.swing.JLabel();
        howToUseTab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        creditLabel = new java.awt.Label();
        exitButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        EditMenu = new javax.swing.JMenu();
        menuClearAll = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Information Encryption Java App");
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(540, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 550));

        inputPlainText.setColumns(20);
        inputPlainText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputPlainText.setLineWrap(true);
        inputPlainText.setRows(5);
        inputPlainText.setWrapStyleWord(true);
        inputPlainText.setPreferredSize(new java.awt.Dimension(240, 150));

        outputEncryptedText.setEditable(false);
        outputEncryptedText.setColumns(20);
        outputEncryptedText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        outputEncryptedText.setLineWrap(true);
        outputEncryptedText.setRows(5);
        outputEncryptedText.setPreferredSize(new java.awt.Dimension(240, 130));

        encryptionEnterStatementLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        encryptionEnterStatementLabel.setText("Enter Statement to Encrypt:");

        encryptionEncryptedTextLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        encryptionEncryptedTextLabel.setText("Encrypted Text Here:");

        encryptionCopyLabel.setText("Ctrl+C to Copy");

        encryptButton.setText("Encrypt Now");
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout encryptionTabLayout = new javax.swing.GroupLayout(encryptionTab);
        encryptionTab.setLayout(encryptionTabLayout);
        encryptionTabLayout.setHorizontalGroup(
            encryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encryptionTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPlainText, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(encryptionEnterStatementLabel)
                    .addComponent(encryptButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(encryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(encryptionTabLayout.createSequentialGroup()
                        .addComponent(outputEncryptedText, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(encryptionTabLayout.createSequentialGroup()
                        .addComponent(encryptionEncryptedTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(encryptionCopyLabel)
                        .addGap(31, 31, 31))))
        );
        encryptionTabLayout.setVerticalGroup(
            encryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encryptionTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptionEnterStatementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encryptionEncryptedTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encryptionCopyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(encryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputEncryptedText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPlainText, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(encryptButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Encryption", encryptionTab);

        decryptionDecryptedText.setEditable(false);
        decryptionDecryptedText.setColumns(20);
        decryptionDecryptedText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decryptionDecryptedText.setLineWrap(true);
        decryptionDecryptedText.setRows(5);
        decryptionDecryptedText.setPreferredSize(new java.awt.Dimension(240, 130));

        decryptionEnterDecryptedText.setColumns(20);
        decryptionEnterDecryptedText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decryptionEnterDecryptedText.setLineWrap(true);
        decryptionEnterDecryptedText.setRows(5);
        decryptionEnterDecryptedText.setPreferredSize(new java.awt.Dimension(240, 150));

        decryptButton.setText("Decrypt Now");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        decryptionEnterDecryptedLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        decryptionEnterDecryptedLabel.setText("Enter Encrypted Text Here:");

        decryptionDecryptedTextLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        decryptionDecryptedTextLabel.setText("Decrypted Text Here:");

        decryptionPasteLabel.setText("Ctrl+V to Paste");

        javax.swing.GroupLayout decryptionTabLayout = new javax.swing.GroupLayout(decryptionTab);
        decryptionTab.setLayout(decryptionTabLayout);
        decryptionTabLayout.setHorizontalGroup(
            decryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decryptionTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decryptionEnterDecryptedText, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(decryptionTabLayout.createSequentialGroup()
                        .addComponent(decryptionEnterDecryptedLabel)
                        .addGap(18, 18, 18)
                        .addComponent(decryptionPasteLabel))
                    .addComponent(decryptButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(decryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decryptionDecryptedText, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptionDecryptedTextLabel))
                .addGap(23, 23, 23))
        );
        decryptionTabLayout.setVerticalGroup(
            decryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decryptionTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decryptionEnterDecryptedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptionDecryptedTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptionPasteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(decryptionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decryptionDecryptedText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptionEnterDecryptedText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decryptButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Decpyrtion", decryptionTab);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Disclaimer: ");

        jLabel8.setText("This application is for experimental use only! Do not use this application ");

        jLabel9.setText("for any offensive work.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Developer will not be responsible for your fault.");

        jLabel11.setText("You can use this application to encrypt your statement in a alphanumeric code!");

        jLabel12.setText("Go to \"Encryption\" Tab and enter your statement in the box under label");

        jLabel13.setText("\"Enter Statement to Encrypt:\" and press \"Encrypt Now\". Then you will get encrypted");

        jLabel14.setText("code in the next text box. Copy that and keep for yourself. To decrept that code, Go to");

        jLabel15.setText("\"Decryption\" tab, paste that and press \"Decrypt Now\". You will get your statement back!!!");

        jLabel16.setText("Encryption works for A-Z, 0-9, dot(.), comma(,), Exclam.(!), at(@), & Ques.(?). ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setText("(not case sensative)");

        javax.swing.GroupLayout howToUseTabLayout = new javax.swing.GroupLayout(howToUseTab);
        howToUseTab.setLayout(howToUseTabLayout);
        howToUseTabLayout.setHorizontalGroup(
            howToUseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(howToUseTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(howToUseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addGroup(howToUseTabLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(howToUseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(howToUseTabLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8)))
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addGroup(howToUseTabLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        howToUseTabLayout.setVerticalGroup(
            howToUseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(howToUseTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(howToUseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(howToUseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(howToUseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("How to use...", howToUseTab);

        creditLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditLabel.setText("Developed by:  Asif Malik");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        EditMenu.setText("Edit");

        menuClearAll.setText("Clear All");
        menuClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearAllActionPerformed(evt);
            }
        });
        EditMenu.add(menuClearAll);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        EditMenu.add(menuExit);

        jMenuBar1.add(EditMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        String plainText = inputPlainText.getText();
        String outputEncryptedText = data.encString(plainText);
        
        
        this.outputEncryptedText.setText(outputEncryptedText);
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        String encryptedText = decryptionEnterDecryptedText.getText();
        String outputDecryptedText = data.decString(encryptedText);
        decryptionDecryptedText.setText(outputDecryptedText);
    }//GEN-LAST:event_decryptButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(1);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearAllActionPerformed
        inputPlainText.setText("");
        decryptionEnterDecryptedText.setText("");
    }//GEN-LAST:event_menuClearAllActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        data = new InfoData();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppJFrame().setVisible(true);
            }
        });
    }
    private static InfoData data;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EditMenu;
    private java.awt.Label creditLabel;
    private javax.swing.JButton decryptButton;
    private javax.swing.JTextArea decryptionDecryptedText;
    private javax.swing.JLabel decryptionDecryptedTextLabel;
    private javax.swing.JLabel decryptionEnterDecryptedLabel;
    private javax.swing.JTextArea decryptionEnterDecryptedText;
    private javax.swing.JLabel decryptionPasteLabel;
    private javax.swing.JPanel decryptionTab;
    private javax.swing.JButton encryptButton;
    private javax.swing.JLabel encryptionCopyLabel;
    private javax.swing.JLabel encryptionEncryptedTextLabel;
    private javax.swing.JLabel encryptionEnterStatementLabel;
    private javax.swing.JPanel encryptionTab;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel howToUseTab;
    private javax.swing.JTextArea inputPlainText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JMenuItem menuClearAll;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JTextArea outputEncryptedText;
    // End of variables declaration//GEN-END:variables
}
